use serde::Serialize;

// ---------------------------------------------------------------------------
// Full rich canonical format — canonical.json
// ---------------------------------------------------------------------------

/// The golden-standard JSON output produced by onset-matcher.
///
/// Describes exactly which MIDI files should play, in what order, with what
/// overlaps, at what beat positions — a jitter-free, instrument-agnostic
/// specification suitable for use as a test fixture.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CanonicalPlaybackReference {
    pub schema_version: String,
    pub name: String,
    pub musical_context: CanonicalMusicalContext,
    pub sources: Vec<CanonicalSource>,
    pub layers: Vec<CanonicalLayer>,
    pub events: Vec<CanonicalEvent>,
    pub onset_clusters: Vec<CanonicalOnsetCluster>,
    pub provenance: ReferenceProvenance,
}

/// Tempo and meter information.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CanonicalMusicalContext {
    pub bpm: f64,
    /// `[numerator, denominator]`, e.g. `[4, 4]`.
    pub time_signature: [u8; 2],
    /// Ticks per quarter note from the MIDI file header.
    pub ppq: u16,
}

/// One MIDI source file referenced by the arrangement.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CanonicalSource {
    pub id: String,
    pub path: String,
    pub length_beats: f64,
}

/// One placed layer on the global beat timeline.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CanonicalLayer {
    pub id: String,
    pub source_id: String,
    pub start_beat: f64,
    pub end_beat: f64,
    pub source_start_beat: f64,
}

/// One MIDI note-on event on the global beat timeline.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CanonicalEvent {
    /// Global beat position.
    pub beat: f64,
    pub source_id: String,
    pub layer_id: String,
    /// Beat within the source MIDI file.
    pub source_beat: f64,
    pub note: u8,
    pub velocity: u8,
}

/// A group of simultaneous events at a beat position, with match quality.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CanonicalOnsetCluster {
    pub beat: f64,
    /// Indices into the `events` array of the parent `CanonicalPlaybackReference`.
    pub event_indices: Vec<usize>,
    /// Normalized expected onset strength from the MIDI template (0.0–1.0).
    pub expected_strength: f64,
    /// Match confidence: 1.0 if an audio onset was found within tolerance, 0.0 otherwise.
    pub confidence: f64,
}

/// Metadata about how this canonical file was generated.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ReferenceProvenance {
    pub generated_by: String,
    pub source_audio: String,
    /// Cluster coverage ratio: matched_clusters / total_clusters.  [0.0, 1.0].
    pub match_score: f64,
    /// `"auto"` unless the file has been human-reviewed and promoted to `"reviewed"`.
    pub review_status: String,
}

// ---------------------------------------------------------------------------
// Flattened test fixture — test-fixture.json
// ---------------------------------------------------------------------------

/// Minimal consumer format for use in unit tests in any language or platform.
///
/// Generated by flattening the canonical event list: all events are grouped
/// by beat cluster, note velocity is omitted, and layer/source IDs are dropped.
///
/// An application under test only needs to capture `(beat, [notes])` tuples
/// from its sequencer output and compare them against this list.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TestFixture {
    pub schema_version: String,
    pub name: String,
    pub bpm: f64,
    /// `[numerator, denominator]`, e.g. `[4, 4]`.
    pub time_signature: [u8; 2],
    pub events: Vec<TestFixtureEvent>,
}

/// One beat cluster in the flattened test fixture.
#[derive(Debug, Clone, Serialize)]
pub struct TestFixtureEvent {
    /// Global beat position.
    pub beat: f64,
    /// Sorted, deduplicated list of MIDI note numbers at this beat.
    pub notes: Vec<u8>,
}
